In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [104]:
import numpy as np
#create aray using numpy
##  create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [105]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [106]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape) # 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [107]:
np.arange(0, 10, 2).reshape(5,1) # start, stop, step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [108]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
## array attributes

arr  = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # 2 rows and 5 columns
print("Number of dimensions:", arr.ndim) # output: 2
print("Data type:", arr.dtype) # output: int32
print("Size:", arr.size) # output: 10
print("Item size:", arr.itemsize, "bytes") # output: 4 bytes (for int32)



Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number of dimensions: 2
Data type: int32
Size: 10
Item size: 4 bytes


In [111]:
## numpy vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# element-wise addition
result_add = arr1 + arr2
print("Addition:", result_add)

# element-wise subtraction
result_del = arr1 - arr2
print("Subtraction:", result_del)

# element-wise multiplication
result_mul = arr1 * arr2
print("Multiplication:", result_mul)

# element-wise division
result_div = arr1 / arr2
print("Division:", result_div)




Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [112]:
## universal functions (ufuncs)

arr = np.array([1, 2, 3, 4, 5])

# square root
resualt_sqrt = np.sqrt(arr)
print("Square root:", resualt_sqrt)

# exponential

result_exp = np.exp(arr)
print("Exponential:", result_exp)


# logarithm
result_log = np.log(arr)
print("Logarithm:", result_log)

# sine
result_sin = np.sin(arr)
print("Sine:", result_sin)


Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [113]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [114]:
arr[0][0]

1

In [115]:

ex1 = arr[1:]  # เอาแถวที่ 1 เป็นต้นถึงแถวสุดท้าย
print("ex1:", ex1)
ex2 = arr[1:,2:]  #เอาแถวที่ 1 เป็นต้นถึงแถวสุดท้าย และเอาคอลัมน์ที่ 2 เป็นต้นถึงคอลัมน์สุดท้าย
print("ex2:", ex2)
ex3 = arr[:,1:3]  #เอาทุกแถว และเอาคอลัมน์ที่ 1 ถึงคอลัมน์ที่ 2
print("ex3:", ex3)
ex4 = arr[1:3,0:2]  #เอาแถวที่ 1 ถึงแถวที่ 2 และเอาคอลัมน์ที่ 0 ถึงคอลัมน์ที่ 1
print("ex4:", ex4)
ex5 = arr[0:1] #เอาแถวที่ เริ่มต้น ถึง ก่อนสุดท้าย
print("ex5:", ex5)


ex1: [[4 5 6]
 [7 8 9]]
ex2: [[6]
 [9]]
ex3: [[2 3]
 [5 6]
 [8 9]]
ex4: [[4 5]
 [7 8]]
ex5: [[1 2 3]]


In [116]:
print(arr[0][0])
print(f"{arr[0:2]}")
print(arr[0:2,1:])

1
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [118]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# modify array elements
arr [0,0]   = 10    #  arr[0] = 10  แบบนี้คือทั้งเเถวจะเป็น 10
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [120]:
arr[1:]=100
print(arr)

[[ 10   2   3]
 [100 100 100]
 [100 100 100]]


In [124]:
## statistics concepts -- Normorlizeation 
## to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# calculate mean and standard deviation

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)


# Variance
variance = np.var(data)
print("Variance:", variance)

# Median
median = np.median(data)
print("Median:", median)



# Noemalize the data 
normalize_data = (data - mean) / std_dev
print("Normalized data:", normalize_data)

# output
# Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]





Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Median: 5.5
Normalized data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [129]:
## Logical operations
data = np.array([1, 2, 3, 4, 5])
data [(data > 3) & (data < 5)]


array([4])